#!/bin/bash

java -Xshareclasses:name=payara-micro,noTimestampChecks \
 -jar ${PAYARA_MICRO_HOME}/payara-micro-${ACTIVE_PAYARA_VERSION}.jar \
 --prebootcommandfile ./MICRO-INF/myjvmcommands.txt \
 --deploy ./target/webui --contextroot /app \
 --logProperties ./MICRO-INF/logging.properties
